---
title: "TP, TN, FP, FN Plot"
author: "Tye Leckinger"
date: "4/6/2023"
output: html_document
---

```{r setup, include=FALSE}
library('tidyverse')
library('ggrepel')
library('grid')
library("cowplot")

```

# Note: for Labels and Guesses, the input must be the same length and should be consisting of 0's and 1's where 0 is negative and 1 is positive

```{r Functions}
Accuracy_Label_Table <- function (Labels, Guesses) {
  Value_P <- function(Label, Guess){
  bin <- as.integer( #Returns int equivalent of binary value Label,Guess
    strtoi(
      paste0(Label * 10 + Guess), 
      base = 2
      )
    )
  
    arr <- c("TN", #Label = 0, Guess = 0
             "FP", #Label = 0, Guess = 1
             "FN", #Label = 1, Guess = 0
             "TP" #Label = 1, Guess = 1
             )
    return(arr[bin+1])
  
  
  }
  
  result <- map2(.x = Labels, .y = Guesses,.f = Value_P) %>% unlist()

  TN_Count <- result[result == "TN"] %>% length()
  FP_Count <- result[result == "FP"] %>% length()
  FN_Count <- result[result == "FN"] %>% length()
  TP_Count <- result[result == "TP"] %>% length()
  
  
  group = c("True Negative (TN)", #Label = 0, Guess = 0
             "False Positive (FP)", #Label = 0, Guess = 1
             "False Negative (FN)", #Label = 1, Guess = 0
             "True Positive (TP)" #Label = 1, Guess = 1
             )
  value = c(TN_Count,
            FP_Count,
            FN_Count,
            TP_Count)
  
  data.frame(group = group,
             value = value)
}
#-------------------------------------------------------------------------------
FP_Pie_Chart <- function(Labels, Guesses) {
  a_table <- Accuracy_Label_Table(Labels = Labels,
                     Guesses = Guesses)

  N_Acc <- round(a_table[1,2] / (a_table[1,2] + a_table[3,2]), digits = 4)
  P_Acc <- round(a_table[4,2] / (a_table[4,2] + a_table[2,2]), digits = 4)
  Acc <- round((a_table[1,2] + a_table[4,2]) / (a_table[1,2] + a_table[3,2] + a_table[4,2] + a_table[2,2]), digits = 4)
  
  plt <- a_table %>%
    ggplot(aes(x = "", y = value, fill = group)) +
    geom_col() + 
    geom_label(aes(label = value),
               position = position_stack(vjust = 0.5),
               show.legend = FALSE) +
    coord_polar(theta = "y") +
    scale_fill_manual(values = c("#FFABAB", "#FFB092",
                                 "#b4d4fa", "#BFFCC6"),
                      guide = guide_legend(reverse = TRUE)) + 
    ggtitle("TP, TN, FP, FN Pie Chart") +
    theme_void()
  
  plt <- ggdraw(plt)
  
  plt <- plt +
    annotation_custom(grob = textGrob(paste0("Accuracy Positive: ",P_Acc)),  xmin = 1 - .2, xmax = 1 - .2, ymin = 1 - .025, ymax = 1- .025) +
    annotation_custom(grob = textGrob(paste0("Accuracy Negative: ",N_Acc)),  xmin = 1 - .2, xmax = 1 - .2, ymin = 1 - .025 - .05, ymax = 1- .025 - .05) +
    annotation_custom(grob = textGrob(paste0("Total Accuracy: ",Acc)),  xmin = 1 - .2, xmax = 1 - .2, ymin = 1 - .025 - .1, ymax = 1- .025 - .1)
  plt
}
#-------------------------------------------------------------------------------
```



```{r Example}

Labels =  sample(0:1,10,replace=TRUE)#250 random values of 1's and 0's
Guesses = sample(0:1,10,replace=TRUE)#250 random values of 1's and 0's



Accuracy_Label_Table(Labels = Labels,
                     Guesses = Guesses)


FP_Pie_Chart(Labels =  Labels,
             Guesses = Guesses)
```
```{r}


library('tidyverse')
library('caret')
library('keras')
library("cowplot")
library('grid')
#library('ggrepel')


Dir_Main <- 'Datasets/Tweets_with_Sarcasm_and_Irony'
Dir_ISarcasm <- 'Datasets/ISarcasm'


tensorflow::tf$python$client$device_lib$list_local_devices() %>% print()


retrieve_dataset <- function(Dir = 'Datasets/Tweets_with_Sarcasm_and_Irony', binary = FALSE) {
  train <- read_csv(paste0(Dir,"/train.csv"))
  
  
  test <- read_csv(paste0(Dir,"/test.csv"))
  test <- test %>% filter(!is.na(class))
  
  factor_set <- function(set) {
    set$class[set$class == 'regular'] = 0
    set$class[set$class == 'sarcasm'] = 1
    
    if(!binary) {
      set$class[set$class == 'figurative'] = 2
      set$class[set$class == 'irony'] = 3
    } else {
      set$class[set$class == 'figurative'] = 1
      set$class[set$class == 'irony'] = 1
    }
    set
  }
  
  
  
  
  
  
  train <- factor_set(train)
  test <- factor_set(test)
  
  index <- createDataPartition(train$class, p = .8, list = FALSE)
  
  train <- train[index,]
  validation <- train[-index,]
  
  
   
  training_labels <- (train$class %>% as.array() %>% as.double()) #normalize
  validation_labels <- (validation$class %>% as.array() %>% as.double()) #normalize
  test_labels <-  (test$class %>% as.array() %>% as.double()) 
  
  
  
  list(train_set = train,
       train_labels = training_labels,
       test_set = test,
       test_labels = test_labels,
       validation_set = validation,
       validation_labels = validation_labels)
}


sets <- retrieve_dataset(binary = TRUE)
train <- sets$train_set




x <- train$tweets
y <- train$class



n_folds <- 10
counter_a = floor(train$class %>% length() / n_folds)

i = 3



#counter = counter_a
#for (k in 1:n_folds) {
  test <- x[counter_a * i:(counter_a * (i + 1))]
  test_labels <- y[counter_a * i:(counter_a * (i + 1))]
  
  train <- x[-c(counter_a * i:(counter_a * (i + 1)))]
  train_labels <- y[-c(counter_a * i:(counter_a * (i + 1)))]

  
  result <- list(train = train,
                 train_labels = train_labels,
                 test = test,
                 test_labels = test_labels)

  
#}



#i = 1









#train <- sets$train_set


#train <- train[-c(1:20),]

#
#crossvalidation <- function(data,labels,  n_folds){
  
  
  
  
  







```

